#!/usr/bin/env bash
# Updates fstubner/homebrew-tap's Formula/netscli.rb to point at the new
# release. Verifies SHA256 for each platform asset against the actual
# downloaded bytes, regenerates the formula, and pushes a single commit
# to the tap.
#
# The formula is regenerated from packaging/homebrew/netscli.rb rather
# than patched in place.
#
# Patching only ever touched `version` and the four `sha256` lines, so
# every other line in the tap's copy was whatever was committed by hand
# when the tap was bootstrapped, and stayed that way through seven
# releases. It still carried a header describing a manual three-step
# release process that no longer exists, naming `VERSION_SHA256_*`
# placeholders the file does not contain, and a `desc` that had since
# diverged from the template. None of that was visible from this repo,
# which is the problem: the template was the reviewed artifact and the
# tap held the shipped one, and nothing kept them equal.
#
# publish-homebrew-cask.sh solves the same problem with a heredoc, which
# means the cask body exists twice. That is not repeated here: this
# template already carries `@@SHA256_*@@` placeholders in exactly the
# positions the digests go, so it can be the single copy.
#
# Required environment:
#   GH_TOKEN — PAT with `repo` scope on fstubner/homebrew-tap.
# Required argument:
#   $1 — tag, e.g. "v0.2.1".

set -euo pipefail

# shellcheck source=scripts/release/lib.sh
. "$(dirname "$0")/lib.sh"

TEMPLATE="$(dirname "$0")/../../packaging/homebrew/netscli.rb"

TAG="${1:?usage: publish-homebrew.sh <tag>}"
validate_tag "$TAG"
VERSION="${TAG#v}"

BASE="https://github.com/fstubner/netscli/releases/download/${TAG}"
ASSETS=(
  "netscli-macos-aarch64"
  "netscli-macos-x86_64"
  "netscli-linux-aarch64"
  "netscli-linux-x86_64"
)

# Placeholder in the template, keyed by asset. The template's own comment
# explains why these are placeholders rather than a previous release's
# digests.
declare -A PLACEHOLDER=(
  ["netscli-macos-aarch64"]="@@SHA256_MACOS_AARCH64@@"
  ["netscli-macos-x86_64"]="@@SHA256_MACOS_X86_64@@"
  ["netscli-linux-aarch64"]="@@SHA256_LINUX_AARCH64@@"
  ["netscli-linux-x86_64"]="@@SHA256_LINUX_X86_64@@"
)

if [[ ! -f "$TEMPLATE" ]]; then
  echo "ERROR: formula template not found at ${TEMPLATE}" >&2
  exit 1
fi

declare -A SHA
for asset in "${ASSETS[@]}"; do
  echo "→ verifying ${asset}"
  SHA[$asset]=$(verified_sha "$BASE" "$asset")
done

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT
clone_tap "fstubner/homebrew-tap" "$WORKDIR/tap"

formula="$WORKDIR/tap/Formula/netscli.rb"
mkdir -p "$(dirname "$formula")"

# The template's header explains that it is a template and how to fill it
# in by hand, which is exactly wrong once it is the installed formula.
# Drop everything above `class Netscli < Formula` and write a header that
# is true of the generated file.
{
  cat <<'EOF'
# Formula for Homebrew, installed from fstubner/homebrew-tap.
#
# Auto-generated by scripts/release/publish-homebrew.sh on every release
# from netscli's packaging/homebrew/netscli.rb — do not hand-edit. Any
# change made here is silently reverted by the next release; change the
# template instead.
#
# Usage:
#   brew tap fstubner/tap
#   brew install netscli
EOF
  sed -n '/^class Netscli < Formula$/,$p' "$TEMPLATE"
} > "$formula"

if ! grep -q '^class Netscli < Formula$' "$formula"; then
  echo "ERROR: template ${TEMPLATE} has no 'class Netscli < Formula' line;" >&2
  echo "       the generated formula would be a comment block and nothing else." >&2
  exit 1
fi

# VERSION passed validate_tag and every digest passed verified_sha, so
# neither can contain the `|` that delimits these replacements.
sed -i -E "s|^  version \"[^\"]+\"|  version \"${VERSION}\"|" "$formula"
for asset in "${ASSETS[@]}"; do
  sed -i "s|${PLACEHOLDER[$asset]}|${SHA[$asset]}|" "$formula"
done

# Sanity check: exactly 4 sha256 lines, each a real 64-char hex digest.
# A count of `^      sha256 "` would also match `sha256 ""`, so match the
# digest itself.
got=$(grep -cE '^      sha256 "[0-9a-f]{64}"$' "$formula" || true)
if [[ "$got" -ne 4 ]]; then
  echo "ERROR: expected 4 valid sha256 lines in formula, got ${got}" >&2
  cat "$formula" >&2
  exit 1
fi
if ! grep -q "^  version \"${VERSION}\"$" "$formula"; then
  echo "ERROR: formula version was not updated to ${VERSION}" >&2
  cat "$formula" >&2
  exit 1
fi
# Any placeholder still present means a substitution above silently
# matched nothing — a renamed placeholder in the template, say.
if grep -q '@@' "$formula"; then
  echo "ERROR: formula still contains unsubstituted placeholders" >&2
  cat "$formula" >&2
  exit 1
fi
# The formula body now comes from a file this script does not parse, so a
# syntax error in the template would reach the tap and break every
# `brew install` until someone noticed. Ruby is present on the runner;
# skip rather than fail if it ever is not.
if command -v ruby >/dev/null 2>&1; then
  if ! ruby -c "$formula" >/dev/null; then
    echo "ERROR: generated formula is not valid Ruby" >&2
    cat "$formula" >&2
    exit 1
  fi
else
  echo "WARNING: ruby not found; skipping the formula syntax check." >&2
fi

cd "$WORKDIR/tap"
git diff -- Formula/netscli.rb
git add Formula/netscli.rb
commit_and_push "netscli ${VERSION}"

echo "✓ Homebrew tap updated to ${VERSION}"
