#!/usr/bin/env bash
# Updates fstubner/homebrew-tap's Casks/netscli-gui.rb to point at the new
# release. Cask file is regenerated wholesale rather than sed-patched
# because the Cask block puts sha256 BEFORE url (opposite of the
# Formula's url-then-sha256), and a single-pass awk pattern that mirrors
# publish-homebrew.sh would need a backwards lookup. Heredoc is simpler
# and produces identical output every release.
#
# Required environment:
#   GH_TOKEN — PAT with `repo` scope on fstubner/homebrew-tap.
# Required argument:
#   $1 — tag, e.g. "v0.2.5".

set -euo pipefail

# shellcheck source=scripts/release/lib.sh
. "$(dirname "$0")/lib.sh"

TAG="${1:?usage: publish-homebrew-cask.sh <tag>}"
validate_tag "$TAG"
VERSION="${TAG#v}"

BASE="https://github.com/fstubner/netscli/releases/download/${TAG}"
ASSETS=(
  "netscli-gui-macos-aarch64.dmg"
  "netscli-gui-macos-x86_64.dmg"
)

declare -A SHA
for asset in "${ASSETS[@]}"; do
  echo "→ verifying ${asset}"
  SHA[$asset]=$(verified_sha "$BASE" "$asset")
done

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT
clone_tap "fstubner/homebrew-tap" "$WORKDIR/tap"
cd "$WORKDIR/tap"

mkdir -p Casks

# The heredoc delimiter is QUOTED, so nothing in the body is expanded by
# the shell — `#{version}` is literal Ruby, and no interpolated value can
# trigger command substitution. The two values we do need to inject are
# substituted afterwards by sed, from variables that have already been
# validated (VERSION via validate_tag) or verified as 64-char hex digests
# (SHA via verified_sha).
cat > Casks/netscli-gui.rb <<'EOF'
# Homebrew Cask for the netscli desktop app (Tauri 2 + React).
#
# Auto-generated by publish-homebrew-cask.sh on every release —
# do not hand-edit. Source template lives in
# netscli's packaging/homebrew/Casks/netscli-gui.rb.

cask "netscli-gui" do
  version "@@VERSION@@"

  on_arm do
    sha256 "@@SHA_ARM@@"
    url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-gui-macos-aarch64.dmg"
  end
  on_intel do
    sha256 "@@SHA_INTEL@@"
    url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-gui-macos-x86_64.dmg"
  end

  name "NetsCLI"
  desc "NetsCLI desktop app for reviewing network scans, DNS, ARP, and local inventory"
  homepage "https://netscli.com"

  app "NetsCLI.app"

  zap trash: [
    "~/Library/Application Support/com.netscli.gui",
    "~/Library/Caches/com.netscli.gui",
    "~/Library/Preferences/com.netscli.gui.plist",
  ]
end
EOF

sed -i \
  -e "s|@@VERSION@@|${VERSION}|" \
  -e "s|@@SHA_ARM@@|${SHA[netscli-gui-macos-aarch64.dmg]}|" \
  -e "s|@@SHA_INTEL@@|${SHA[netscli-gui-macos-x86_64.dmg]}|" \
  Casks/netscli-gui.rb

# Sanity check: the version we expect, exactly two sha256 lines that are
# real 64-char hex digests, and no leftover placeholders. The old check
# counted `^    sha256 "`, which also matches `sha256 ""`.
got_ver=$(grep -c "^  version \"${VERSION}\"$" Casks/netscli-gui.rb || true)
got_sha=$(grep -cE '^    sha256 "[0-9a-f]{64}"$' Casks/netscli-gui.rb || true)
if [[ "$got_ver" -ne 1 || "$got_sha" -ne 2 ]]; then
  echo "ERROR: cask render check failed (version lines=${got_ver}, sha lines=${got_sha})" >&2
  cat Casks/netscli-gui.rb >&2
  exit 1
fi
if grep -q '@@' Casks/netscli-gui.rb; then
  echo "ERROR: cask still contains unsubstituted placeholders" >&2
  cat Casks/netscli-gui.rb >&2
  exit 1
fi

# The token moved from `netscli` to `netscli-gui`; retire the old file the
# first time this runs against a tap that still has it, or the tap keeps a
# formula and a cask sharing one token and `brew install netscli` stays
# ambiguous.
if [[ -f Casks/netscli.rb ]]; then
  echo "Removing the superseded Casks/netscli.rb (token renamed to netscli-gui)."
  git rm --quiet Casks/netscli.rb
fi

git diff --cached Casks/ || true
git diff Casks/netscli-gui.rb
git add Casks/netscli-gui.rb
commit_and_push "netscli-gui ${VERSION} (Cask)"

echo "✓ Homebrew Cask updated to ${VERSION}"
