#!/usr/bin/env bash
# Updates fstubner/homebrew-tap's Casks/netscli.rb to point at the new
# release. Cask file is regenerated wholesale rather than sed-patched
# because the Cask block puts sha256 BEFORE url (opposite of the
# Formula's url-then-sha256), and a single-pass awk pattern that mirrors
# publish-homebrew.sh would need a backwards lookup. Heredoc is simpler
# and produces identical output every release.
#
# Required environment:
#   GH_TOKEN — PAT with `repo` scope on fstubner/homebrew-tap.
# Required argument:
#   $1 — tag, e.g. "v0.2.5".

set -euo pipefail

TAG="${1:?usage: publish-homebrew-cask.sh <tag>}"
VERSION="${TAG#v}"

BASE="https://github.com/fstubner/netscli/releases/download/${TAG}"
ASSETS=(
  "netscli-gui-macos-aarch64.dmg"
  "netscli-gui-macos-x86_64.dmg"
)

# Same polling pattern as publish-homebrew.sh: release.yml's GUI matrix
# can take 5-10 minutes (Tauri compile + bundle), so we tolerate up to
# 15 minutes of asset-not-yet.
wait_for_asset() {
  local url="$1"
  local i
  for i in {1..30}; do
    if curl -fsSL --head "$url" >/dev/null 2>&1; then
      return 0
    fi
    echo "  not yet; retry in 30s ($i/30)"
    sleep 30
  done
  echo "ERROR: $url never became available" >&2
  return 1
}

declare -A SHA
for asset in "${ASSETS[@]}"; do
  url="${BASE}/${asset}.sha256"
  echo "→ ${url}"
  wait_for_asset "$url"
  SHA[$asset]=$(curl -fsSL "$url" | awk '{print $1}')
done

WORKDIR=$(mktemp -d)
trap 'rm -rf "$WORKDIR"' EXIT
git clone --depth 1 \
  "https://x-access-token:${GH_TOKEN}@github.com/fstubner/homebrew-tap.git" \
  "$WORKDIR/tap"
cd "$WORKDIR/tap"
git config user.name  "netscli release bot"
git config user.email "noreply@netscli.com"

mkdir -p Casks
cat > Casks/netscli.rb <<EOF
# Homebrew Cask for the netscli desktop app (Tauri 2 + React).
#
# Auto-generated by publish-homebrew-cask.sh on every release —
# do not hand-edit. Source template lives in
# netscli's packaging/homebrew/Casks/netscli.rb.

cask "netscli" do
  version "${VERSION}"

  on_arm do
    sha256 "${SHA[netscli-gui-macos-aarch64.dmg]}"
    url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-gui-macos-aarch64.dmg"
  end
  on_intel do
    sha256 "${SHA[netscli-gui-macos-x86_64.dmg]}"
    url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-gui-macos-x86_64.dmg"
  end

  name "NetsCLI"
  desc "NetsCLI desktop app for reviewing network scans, DNS, ARP, and local inventory"
  homepage "https://netscli.com"

  app "NetsCLI.app"

  zap trash: [
    "~/Library/Application Support/com.netscli.app",
    "~/Library/Caches/com.netscli.app",
    "~/Library/Preferences/com.netscli.app.plist",
  ]
end
EOF

# Sanity check: file has the version we expect AND exactly two sha256
# lines (one per arch).
got_ver=$(grep -c "^  version \"${VERSION}\"$" Casks/netscli.rb || true)
got_sha=$(grep -c '^    sha256 "' Casks/netscli.rb || true)
if [[ "$got_ver" -ne 1 || "$got_sha" -ne 2 ]]; then
  echo "ERROR: cask render check failed (version lines=${got_ver}, sha lines=${got_sha})" >&2
  cat Casks/netscli.rb >&2
  exit 1
fi

git diff Casks/netscli.rb
git add Casks/netscli.rb
git commit -m "netscli-gui ${VERSION} (Cask)"
git push origin HEAD

echo "✓ Homebrew Cask updated to ${VERSION}"
