use anyhow::{Context, Result};
use clap::CommandFactory;
use clap_complete::Shell;
use std::io::{self, Write};

pub(super) fn print_completions<T: CommandFactory>(shell: Shell) {
    let mut cmd = T::command();
    let name = cmd.get_name().to_string();
    clap_complete::generate(shell, &mut cmd, name, &mut io::stdout());
}

pub(super) fn print_man<T: CommandFactory>() -> Result<()> {
    let cmd = T::command();
    let man = clap_mangen::Man::new(cmd);
    man.render(&mut io::stdout())
        .context("rendering man page")?;
    Ok(())
}

/// Generated by scripts/third-party-notices.mjs, which CI keeps in step with
/// Cargo.lock. It sits inside this crate so the crates.io package has it too.
const THIRD_PARTY_NOTICES: &str = include_str!("../../THIRD-PARTY-NOTICES.txt");

pub(super) fn print_licenses() -> Result<()> {
    match io::stdout().write_all(THIRD_PARTY_NOTICES.as_bytes()) {
        // The file is long, so it is read through `less` or `head`, and
        // quitting either closes the pipe before it is all written.
        Err(error) if error.kind() == io::ErrorKind::BrokenPipe => Ok(()),
        result => result.context("printing the license notices"),
    }
}
