# Formula for Homebrew. After cutting release vX.Y.Z:
# 1. Update `version`.
# 2. Replace each `sha256` value with the real SHA256 of the matching
#    platform asset (read from the `.sha256` files on the release page).
# 3. Publish this file in fstubner/homebrew-tap (or submit to
#    homebrew-core once the project has a few releases under its belt).
#
# Usage after tap is published:
#   brew tap fstubner/tap
#   brew install netscli

class Netscli < Formula
  desc "Network diagnostics CLI, terminal UI, and MCP server"
  homepage "https://netscli.com"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-macos-aarch64"
      sha256 "66935b1b627e5e58d7d24ef92f8153381dcbbf06ff79807314ddce47a73a7907"
    end
    on_intel do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-macos-x86_64"
      sha256 "4e136a0b3fd287d7a86f70983c1be5bb4bd56f6c9d4f7b4da73e7bad23b644a3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-linux-aarch64"
      sha256 "26f3d174b533d826deff96dc095b2c6067029baaecf757aef2fc227fa846d924"
    end
    on_intel do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-linux-x86_64"
      sha256 "b3e7c97722982a1b7538866d05f7b51094a8b80fd049508e7e3f1f840e40e730"
    end
  end

  def install
    # Asset is the bare binary — rename and mark executable.
    asset_name = if OS.mac?
      Hardware::CPU.arm? ? "netscli-macos-aarch64" : "netscli-macos-x86_64"
    else
      Hardware::CPU.arm? ? "netscli-linux-aarch64" : "netscli-linux-x86_64"
    end
    bin.install asset_name => "netscli"

    # Shell completions + man page generated by the binary itself.
    generate_completions_from_executable(bin/"netscli", "completions")
    (buildpath/"netscli.1").write Utils.safe_popen_read(bin/"netscli", "man")
    man1.install "netscli.1"
  end

  test do
    assert_match "netscli #{version}", shell_output("#{bin}/netscli --version")
  end
end
